version: '3'

services:
###> doctrine/doctrine-bundle ###
  apps:
    container_name: dtc-app
    build:
      context: docker/app
    ports:
      - "83:80"
    volumes:
      - ./:/var/www/dtc-app:rw+
      - ./docker/apache_conf:/etc/apache2/sites-enabled

  mailer:
    container_name: dtc-mailer
    image: schickling/mailcatcher
    ports:
      - "8082:1025"
      - "8083:1080"

  database:
    image: mysql:latest
    container_name: dtc_db
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: julkwel
      MYSQL_DATABASE: dtc-app
      MYSQL_USER: dtc-app
      MYSQL_PASSWORD: dtc@db202e
    volumes:
      - "$PWD/data:/var/lib/mysql:rw"
